version: '3'

services:
    iobroker:
        build: ./iobroker
        container_name: iobroker-valloxmv
        hostname: iobroker-valloxmv
        # This port is only internal, so we can work on this while another instance of ioBroker is running on the host
        expose:
            - 8081
        volumes:
            - ..:/workspace:cached
            # persisting state in a volume will defeat rebuild container
          #  - iobrokerdata-valloxmv:/opt/iobroker
        environment:
            - IOB_OBJECTSDB_TYPE=jsonl
            - IOB_OBJECTSDB_HOST=127.0.0.1
            - IOB_OBJECTSDB_PORT=29001
            - IOB_STATESDB_TYPE=jsonl
            - IOB_STATESDB_HOST=127.0.0.1
            - IOB_STATESDB_PORT=29000
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US:en
            - LC_ALL=en_US.UTF-8
            - TZ=Europe/Berlin
            - SETGID=1000
            #- SETUID=1000

    # Reverse proxy to load up-to-date admin sources from the repo
    nginx:
        image: nginx:latest
        depends_on:
            - iobroker
        links:
            - iobroker
        container_name: nginx-valloxmv
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ..:/workspace:cached
        ports:
            # Make the ioBroker admin available under http://localhost:8082
            - 8082:80

#volumes:
  #  iobrokerdata-valloxmv: